{% set version = "0.2" %}
package:
  name: pygridtools
  version: {{ version }}

source:
  url: https://github.com/Geosyntec/pygridtools/archive/v{{ version }}.tar.gz
  sha256: 8a5d23c01b1d54bf14d7d62304d7321d84d66657e80864bb2453f42402ed40e1

build:
  number: 1004
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6,<3.12
    - pip
  run:
    - python >=3.6,<3.12
    - numpy
    - scipy
    - matplotlib-base
    - fiona
    - pandas
    - geopandas
    - gridgen
    - pygridgen
    # fixme: this should be removed upstream!
    - nose 

test:
  imports:
    - pygridtools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Geosyntec/pygridtools
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Miscellaneous utilities built upon pygridgen

extra:
  recipe-maintainers:
    - ocefpaf
    - phobson
