travis:
  secure:
    BINSTAR_TOKEN: 0n/E6+hnHaxbahVX/1kcbFBdFFNnrZK8kOVvFDZFEg/sYKBs4HvpFN/uGaw/vckmw/GZuXVfmYxxH6yNnrK0goFxQmZD1PiFPgVNNPY8VmQ0IndovwCNvsXGzrMkMXXljCTPcuNCs5y9c0x4ZhzCmko9aDBtfXl/CxOumY3TW2QrEndImfsjSiqYknvKP9xm3CUAiBvk97dQi7GpG2FLGE5y35kYgjA467jnzOQBxrMcMUGOqz+ntS0Myv4EFTLCqKJWP8tcafz1uUHwG2EbIAzdnCaHLf+A8kYnbo8ZsakBjGQM//ktlki2MQRFUOWBBUnd0jtsABFqQUj1xP+DOHhIWQwxiZHTD7BYMKqAQ+/+d8tY/wEqEa5AhYBnB2uXNiwuvJh6XZBPmXUEutCaH+CZTHgN3Ch4W6+C4RX2BZe4w9pkotyBPtnyENH16Es6XWUn9oQStIQUJ89JdNe9hdvOCFqQsj53Ts6Zdqb5U4XTrJ8xjK/1USlQ/xg2KbNX3+HJiAkHpyaXJbGb26B/IssUZfEWM6+l1DnmE+R/pjKFTcFRa4ECbGdipyCf84QoA7GONzJJdy+7pyhPtRRSI7FgDfdiuGbrFpXeQZav4Av9xJPsJQerl+N9+eTFefnDixTNAdpKI5dc3ZL1wkhIeOZykuT+JUBpAgH6Mmt4eVo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
