appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: dAXnVNWhnLupu1UINJEdGHNEwFRu0IlJYkpxu/R8eOj0KWGYyOfgV5fPk7C5qAxLmXc2VT6U4fOKNWR22hWX+12+iMA6gn68Vv7t4GI+DtwIKuBdSULym6twoxU9AFO7fPfxIceE3e2Dk/cJRd+VZHrNkPEu7TfLd42MrH8X2VCw90cdgdFmEdD3FZU3dOb8re9+LrBD0cnROZs9GTtyLmH9cOYvIzfoVelopGoX3Y7w+NzMsqds42mLIoQyPUo4qCu5GnAupZrwOlDYbd0T25NMlXV9GTTDZQZLutrcWTHOWfDEr6wb8j+NHwIW+QW/onLPR+9+73/NycPZ9cKW2E+yqtRH9oXaRJ6MdqSIJh1hlOCSjVgVUpXEfxzGu96O3Wl7LSLATfLStojEXtuyvY6cP8nCs8KX1LLnx0wu9rnfxtjeXfKTYpkuTUxxUIgG5X/RQbnVpO+o+A8qjk4VSf8/iTVE59VrabIHmfHw5lZY5H0apvae3hWYdkPIrg1MNx8Iaz5Fk0RwurbUmcLQXjoosLUDW7ITfwFa1CoSmfFQypbYUL9O/QlClNYhJbFmiIX55l46/60dYwSAdHZrJQZKmEn+iQf1Rb8HsbYkxkcjqPMKT6NnbieygwDzcpklh380/zs8TKxg0YwzG22YeTloRovKFdeTniuMLy9bqYw=}
